# Generated by Django 5.2 on 2025-05-15 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('level', models.CharField(choices=[('beginner', "Boshlang'ich"), ('intermediate', 'O‘rta daraja'), ('advanced', 'Yuqori daraja')], default='beginner', max_length=20)),
                ('color', models.CharField(blank=True, max_length=20, null=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='direction_icons/')),
                ('visibility', models.CharField(choices=[('new', 'Yangi'), ('active', 'Faol'), ('inactive', 'Faol emas')], default='new', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('direction', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('last_active', models.DateTimeField(blank=True, null=True)),
                ('permission', models.BooleanField(default=False)),
                ('extra', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
