# Generated by Django 5.2 on 2025-05-15 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapi', '0002_direction_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimpleQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SimpleTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('duration', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='OralTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('duration', models.PositiveIntegerField()),
                ('pass_score', models.PositiveIntegerField()),
                ('question_count', models.PositiveIntegerField()),
                ('difficulty', models.CharField(choices=[('easy', 'Oson'), ('medium', 'O‘rta'), ('hard', 'Qiyin')], default='medium', max_length=20)),
                ('shuffle', models.BooleanField(default=False)),
                ('show_answers', models.BooleanField(default=False)),
                ('allow_back', models.BooleanField(default=False)),
                ('questions_file', models.FileField(blank=True, null=True, upload_to='oral_tests/')),
                ('topics', models.ManyToManyField(to='authapi.direction')),
            ],
        ),
        migrations.CreateModel(
            name='SimpleChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='authapi.simplequestion')),
            ],
        ),
        migrations.AddField(
            model_name='simplequestion',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='authapi.simpletest'),
        ),
    ]
