# Generated by Django 5.2 on 2025-05-15 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tr', models.CharField(choices=[('T', 'Talaba'), ('R', 'Rəhbariyat')], max_length=1)),
                ('ism_familiya', models.CharField(max_length=100)),
                ('yonalish', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefon', models.CharField(max_length=20)),
                ('songi_faollik', models.DateTimeField(auto_now=True)),
                ('ruxsat', models.BooleanField(default=True)),
                ('qoshimcha', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
